comments/urls.py
from django.urls import path
from .views import Comments

app_name = 'comments'

urlpatterns = [
    path('', Comments.as_view(), name='all')
]

myblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', TemplateView.as_view(template_name='publications/home.html'), name='home'),
    path('users/', include('users.urls', namespace='users')),
    path('publications/', include('publications.urls', namespace='publications')),
    path('comments/', include('comments.urls', namespace='comments'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

publications/urls.py
from django.urls import path, include
from .views import PublicationsView, PublicationsDetail

app_name = 'publications'

urlpatterns = [
    path('', PublicationsView.as_view(), name='home'),
    path('<int:pk>/', PublicationsDetail.as_view(), name='detail'),
]

users/urls.py
from django.urls import path
from .views import UsersHome, UsersShowAll, UsersDetail

app_name = 'users'

urlpatterns = [
    path('home', UsersHome.as_view(), name='home'),
    path('<pk>/', UsersDetail.as_view(), name='user_detail'),
    path('all', UsersShowAll.as_view(), name='all')
]

comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        'users.User', on_delete=models.CASCADE
    )
    content = models.TextField()
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    publication = models.ForeignKey(
        'publications.Publication', on_delete=models.CASCADE
    )

    def __str__(self):
        return '{} -> {}'.format(self.created_by, self.publication)

publications/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Publication(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        'users.User', on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    content = models.TextField()
    stars = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ]
    )

    def __str__(self):
        return self.title

users/models.py
from django.db import models

#
# user123
#
# admin123
#
# example@example.com
#

# Create your models here.
class User(models.Model):
    MALE = 'm'
    FEMALE = 'f'
    GENDER_CHOICES = [
        (MALE, 'male'),
        (FEMALE, 'female')
    ]
    
    created_at = models.DateField(auto_now=True)
    name = models.CharField(max_length=80)
    slug = models.SlugField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    def __str__(self):
        return self.name

class ImageUser(models.Model):
    user = models.ForeignKey(
        'users.User', on_delete=models.CASCADE,
        related_name = 'images'
    )
    image = models.ImageField()

comments/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Comment

# Create your views here.
class Comments(ListView):
    model = Comment
    template_name = 'comments/comments.html'

publications/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from .models import Publication

# Create your views here.
class PublicationsView(ListView):
    model = Publication
    template_name = 'publications/publications.html'

class PublicationsDetail(DetailView):
    model = Publication
    template_name = 'publications/public_detail.html'

users/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, ListView
from .models import User

# Create your views here.
class UsersHome(TemplateView):
    template_name = 'users/home.html'

    def get_context_data (self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_detail'] = User.objects.all()
        return context

class UsersDetail(DetailView):
    model = User

class UsersShowAll(ListView):
    model = User
    template_name = 'users/show.html'
    # export object_list

comments/templates/comments/comments.html
<div>
  <h1>hola</h1>
  {% for comment in object_list %}
    {{ comment.content }}
    {{ comment.created_by }}
  {% endfor %}

</div>

publications/templates/publications/home.html
{% extends "users/base.html" %}

{% block title %}
  Home
{% endblock title %}

{% block content %}

<div class="section no-pad-bot principal" id="index-banner">
  <div class="container">
    <h1 class="header center orange-text">Bienvenido a My-DjangoBlog</h1>
    <!--<ul>
      <li><a href="{% url 'users:home' %}">Go to users</a></li>
      <li><a href="{% url 'publications:home' %}">Go to publications</a></li>
    </ul>-->
    <div class="row center">
      <h5 class="header col s12 light">Hecho en Django + MaterializeCSS</h5>
    </div>
    <div class="row center">
      <a href="#" id="starter-button" class="btn-large waves-effect waves-light orange">Registrate en el Blog</a>
    </div>
    <br><br>
  </div>
</div>


<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row contain-django">
      <div class="orange white-text center ">
        <h2>Porque Django ?</h2>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Rapido Desarrollo</h5>

          <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
          <h5 class="center">Codigo mantenible</h5>

          <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">De facil administracion </h5>

          <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
        </div>

      </div>
    </div>
    <br>
  </div>  
</div>

<style>
  .contain-django {
    margin-top: 10px;
    margin-bottom: 10px;
    padding-top: 20px;
    padding-bottom: 50px;
  }

  .contain-django h2 {
    padding: 15px 0 ;
  }

  .principal {
    padding-top: 50px;
    padding-bottom: 50px !important;
  }
</style>

{% endblock content %}

publications/templates/publications/public_detail.html
{% extends "users/base.html" %}

{% block content %}

    <div class="center">
      <h1>{{ object.title }}</h1>
      <h2>{{ object.created_by }}</h2>
      <p>{{ object.content }}</p>
      <h3>{{ object.stars }}</h3>
    </div>  

    
    {% include 'comments/comments.html' %}

{% endblock content %}

publications/templates/publications/publications.html
{% extends "users/base.html" %}

{% block content %}

  <div class="container">
    <!--<div class="center">-->
    {% for public in object_list %}
      <div class="row">
        <div class="card">
          <div class="center">
            <div class="z-depth-3 white-text pink">
              <h1>{{ public.title }}</h1>
            </div>
            <!-- img -->
            <div class="col s2">
              <img src="" alt="">
            </div>
            <div class="col s10">
              <h2 class="card-title">{{ public.created_by }}</h2>
            </div>
            <div class="card-container">
              <p>{{ public.content }}</p>
            </div>
            <div class="card-action details"><a href='#'>Get details</a></div>
          </div>
        </div>  
      </div>  
    {% endfor %}
  </div>
  <style>

    .details a {
      font-size: 18px;
      text-decoration: underline;
    }

  </style>

<!--  <a href="{% url 'home' %}">Go to Home</a>-->

{% endblock content %}

users/templates/users/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{% static "materialize/css/materialize.min.css" %}">
  {% block styles %}{% endblock styles %}
</head>
<body>

  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="{% url "home" %}" class="brand-logo">My Blog</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/home">Go to Home</a></li>
        <li><a href="{% url 'users:home' %}">Go to User</a></li>
        <li><a href="{% url 'publications:home' %}">Go to Publications</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="{% url 'users:home' %}">Go to Home</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>

<style>
    ul li a {
    font-size: 17px !important;
  }

  .icon-block {
    padding: 0 15px;
  }
  .icon-block .material-icons {
    font-size: inherit;
  }
</style>
 

  {% block content %}
  {% endblock content %}



<footer class="page-footer orange">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Non Company</h5>
        <p class="grey-text text-lighten-4">User materialize para el frontend de este proyecto </p>
      </div>

      <div class="col l3 s12">
        <h5 class="white-text">Settings</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>

      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>

    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
    </div>
  </div>
</footer>
  


  {% block js %}

  {% endblock js %}
  <script src="{% static "materialize/js/materialize.min.js" %}"></script>

</body>
</html>

users/templates/users/home.html
{% extends "users/base.html" %}

{% block content %}
    <div class='container'>
        <div class="">
            <h1>Bienvenido/a {{ name }}</h1>
        </div>
        <div class="">
            <img src="" alt="">
        </div>
        <div>
            
        </div>
        
    </div>

{% endblock content %}

users/templates/users/show.html
{% block content %}
  
    {% for object in object_list %}
      <p>{{ object.name }}</p>
      <p>{{ object.gender }}</p>
    {% endfor %}

{% endblock content %}

users/templates/users/user_detail.html
{% extends "users/base.html" %}

{% block content %}
  <h1>{{ object.name }}</h1>
{% endblock content %}